streamlit:
  data_fld: "assets"
  model: "palm_recognition.onnx"
  img_mean: [0.5, 0.5, 0.5]
  img_std: [0.5, 0.5, 0.5]
  img_crop: [224, 224]
  threshold: 0.8
  rmbg_model: "u2netp" #["u2net", "u2netp", "u2net_human_seg", "u2net_cloth_seg", "silueta"]