trainval:
  train_csv: "./data/trainval.csv"
  val_csv: "./data/val.csv"
  test_csv: "./data/test.csv"
  tot_data_file: 'hand_augId370.csv'
  mlflow: "local"
  fold: 1
  specify_hand_side: null
  experiment_name: "mobilenet_1fold_s40_d360_bs96_e50_adam"
  is_validate: true
  val_register_num: 1
  log_interval: 10
  gpu_type: "mps"
  batchsize: 96
  n_worker: 0
  arcface_m: 0.5
  arcface_s: 40
  embedding_size: 512
  net_depth: 50
  drop_ratio: 0.6
  pretrained: "model_mobilefacenet.pth"
  net_mode: "mobilefacenet"
  loss_type: "CrossEntropyLoss"
  epoch: 50
  opt: "SGD"
  opt_params:
    lr: 0.0025
    momentum: 0.9
    weight_decay: 0.0005
  lr_sched: "MultiStepLR"
  lr_sched_params:
    milestones: [30, 40, 45]
    gamma: 0.1
  img_resize: [117, 117]
  img_crop: [112, 112]
  img_rflip_p: 0.5
  img_vflip_p: 0.5
  img_mean: [0.5, 0.5, 0.5]
  img_std: [0.5, 0.5, 0.5]