trainval:
  train_csv: null
  val_csv: null
  test_csv: null
  tot_data_file: 'hand_augId370.csv'
  mlflow: "local"
  fold: 5
  specify_hand_side: null
  experiment_name: "mobile_5fold_s40_d224_bs48_e10_sgd_grayscale"
  is_validate: true
  val_register_num: 1
  log_interval: 10
  gpu_type: "mps"
  batchsize: 36
  n_worker: 0
  arcface_m: 0.5
  arcface_s: 40
  embedding_size: 512
  net_depth: 50
  drop_ratio: 0.6
  pretrained: "model_mobilefacenet.pth"
  net_mode: "mobilefacenet"
  loss_type: "CrossEntropyLoss"
  epoch: 10
  opt: "SGD"
  opt_params:
    lr: 0.003
    momentum: 0.9
    weight_decay: 0.0005
  lr_sched: "MultiStepLR"
  lr_sched_params:
    milestones: [6, 8]
    gamma: 0.1
  img_resize: [240, 240]
  img_crop: [224, 224]
  img_rflip_p: 0.5
  img_vflip_p: 0.5
  img_mean: [0.5, 0.5, 0.5]
  img_std: [0.5, 0.5, 0.5]
  brightness: [0.8, 1.2]
  contrast: [0.8, 1.2]
  saturation: [0.8, 1.2]
  grayscale: true